version: '2'

services:
    db:
        image: postgres:alpine
        volumes:
           - ./data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
    php:
        build: php7-fpm
        volumes:
            - ./symfony:/var/www/symfony
    nginx:
        build: nginx
        ports:
            - 80:80
