version: '2'

services:
    db:
        image: postgres:alpine
        volumes:
           - ./data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
    php:
        build: php7-fpm
        volumes:
            - symfony-sync:/var/www/symfony:nocopy
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./nginx/main.template:/etc/nginx/main.template
        volumes_from:
            - php
        environment:
            NGINX_HOST: ${NGINX_HOST}
            APP_ENTRY_POINT: ${APP_ENTRY_POINT}
        command: /bin/sh -s "envsubst < /etc/nginx/main.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
volumes:
    symfony-sync:
        external: true
