<?php
declare(strict_types=1);

namespace AppBundle\Repository;

/**
 * ArticleLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
