#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

app_rest:
    type: rest
    resource: "dictionaries_routes.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
