version: '3.1'

services:
  db:
    image: postgres:9-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: nopass
    ports:
      - 5433:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
